# Generated by Django 3.2.9 on 2021-12-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('km', models.CharField(max_length=150)),
                ('valor', models.CharField(max_length=150)),
            ],
        ),
    ]
